/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

import com.google.common.base.Preconditions;
import entidades.Funcionario;
import entidades.Rota;
import interfacesBean.FuncionarioBeanInterface;
import interfacesBean.RotaBeanInterface;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class ManutencaoRotas extends javax.swing.JFrame {

    /**
     * Creates new form ManutencaoRotas
     */
    public ManutencaoRotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboHorario = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        novoHorarioRota = new javax.swing.JTextField();
        alterarHorario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rgFuncionario = new javax.swing.JTextField();
        incluirFuncionario = new javax.swing.JButton();
        IncluirRota = new javax.swing.JButton();
        comboOrigem = new javax.swing.JComboBox();
        comboDestino = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        datas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        horario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboOrigemHorario = new javax.swing.JComboBox();
        comboDestinoHorario = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        comboPreco = new javax.swing.JComboBox();
        carregarRotas = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        comboDataHorario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Manutenção das Rotas:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Incluir nova Rota:");

        jLabel4.setText("Origem:");

        jLabel5.setText("Destino:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Alterar Horário:");

        jLabel7.setText("Selecionar Data:");

        jLabel8.setText("Novo Horário:");

        alterarHorario.setText("Alterar Horário");
        alterarHorario.setActionCommand("btnHorario");
        alterarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarHorarioActionPerformed(evt);
            }
        });

        jButton3.setText("Retornar ao Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Incluir Funcionário:");

        jLabel10.setText("Nome:");

        jLabel11.setText("RG:");

        incluirFuncionario.setText("Incluir Funcionário");
        incluirFuncionario.setActionCommand("btnFuncionario");
        incluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirFuncionarioActionPerformed(evt);
            }
        });

        IncluirRota.setText("Incluir Rota");
        IncluirRota.setActionCommand("btnRota");
        IncluirRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirRotaActionPerformed(evt);
            }
        });

        comboOrigem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Araraquara", "Campinas", "Ribeirao Preto", "Santos", "Sao Paulo" }));

        comboDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Araraquara", "Campinas", "Ribeirao Preto", "Santos", "Sao Paulo" }));

        jLabel12.setText("Data:");

        datas.setText("dd-mm-aaaa");

        jLabel13.setText("Horário:");

        horario.setText("hh:mm");

        jLabel14.setText("Origem:");

        jLabel15.setText("Destino:");

        comboOrigemHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Araraquara", "Campinas", "Ribeirao Preto", "Santos", "Sao Paulo" }));

        comboDestinoHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Araraquara", "Campinas", "Ribeirao Preto", "Santos", "Sao Paulo" }));

        jLabel16.setText("Preço:");

        comboPreco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "25.3", "21.0", "25.3", "19.9" }));

        carregarRotas.setText("Carregar Horários");
        carregarRotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarRotasActionPerformed(evt);
            }
        });

        jLabel17.setText("Selecionar Horario:");

        comboDataHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDataHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(horario, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addComponent(datas, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(comboDestino, 0, 123, Short.MAX_VALUE)
                                        .addComponent(comboOrigem, 0, 123, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IncluirRota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(novoHorarioRota)
                                                    .addComponent(comboHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(comboDataHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(comboDestinoHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(comboOrigemHorario, 0, 111, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(carregarRotas)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel10))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(rgFuncionario)
                                                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                                    .addComponent(incluirFuncionario))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(alterarHorario)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(comboOrigemHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(comboDestinoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carregarRotas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(rgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(datas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboDataHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incluirFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(comboPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(novoHorarioRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncluirRota)
                            .addComponent(alterarHorario))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ações de gravação de Rota
    private void IncluirRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirRotaActionPerformed
        RotaBeanInterface rotaBean = null;      
        InitialContext ctx = null;
        
        try {
            ctx = new InitialContext();
            rotaBean = (RotaBeanInterface) ctx.lookup("ejb/RotaBean");
            String horarioRota = horario.getText();
            String dataRota = datas.getText();
            String origemRota = (String) comboOrigem.getSelectedItem();
            String destinoRota = (String) comboDestino.getSelectedItem();
            double precoRota = Double.parseDouble((String) comboPreco.getSelectedItem());
            
            Rota rota = new Rota();
            rota.setDatas(dataRota);
            rota.setDestinoRota(destinoRota);
            rota.setOrigemRota(origemRota);
            rota.setPreco(precoRota);
            rota.setHorario(horarioRota);

            if(rotaBean.cadastrarRota(rota))
                JOptionPane.showMessageDialog(rootPane, "Rota Incluida");
            else
                JOptionPane.showMessageDialog(rootPane, "Rota não pode ser incluida");
            
            } catch (NamingException ex) {
            Logger.getLogger(ManutencaoRotas.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_IncluirRotaActionPerformed

    //Ações de gravação de novo Horário
    private void alterarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarHorarioActionPerformed
        RotaBeanInterface rotaBean = null;
        InitialContext ctx = null;
        List<Rota> lista;
        
        String origem = (String) comboOrigemHorario.getSelectedItem();
        String destino = (String) comboDestinoHorario.getSelectedItem();
        String horarioRota = (String) comboHorario.getSelectedItem();
        String data = (String) comboDataHorario.getSelectedItem();
        
        String horarioAlterar = novoHorarioRota.getText();
        
        try {
            ctx = new InitialContext();
            rotaBean = (RotaBeanInterface) ctx.lookup("ejb/RotaBean");
            
            if(rotaBean.alterarHorario(horarioRota, horarioAlterar, origem, destino, data)){
                JOptionPane.showMessageDialog(rootPane, "Horário alterado com sucesso.");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Horário não pode ser alterado");
            }
        
        } catch (NamingException ex) {
            Logger.getLogger(TelaVendaHorario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_alterarHorarioActionPerformed

    //Ações de gravação de um novo funcionário
    private void incluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirFuncionarioActionPerformed
        
        InitialContext ctx = null;
        FuncionarioBeanInterface funcionarioBean = null;
       
        Funcionario funcionario;
        long rg = Long.parseLong(rgFuncionario.getText());
        String nome = nomeFuncionario.getText();
        try {
            ctx = new InitialContext();
        
            funcionarioBean = (FuncionarioBeanInterface)ctx.lookup("ejb/FuncionarioBean");
                        
            funcionario = new Funcionario(nome, rg);      
            
            if(funcionarioBean.cadastrarFuncionario(funcionario)){
                JOptionPane.showMessageDialog(rootPane, "Funcionário cadastrado com sucesso.");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Funcionário não pode ser cadastrado");
            }
            
        } catch (NamingException ex) {
            Logger.getLogger(ManutencaoRotas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_incluirFuncionarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ManutencaoRotas.this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

private void carregarRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarRotasActionPerformed
        comboDataHorario.removeAllItems();
        comboHorario.removeAllItems();
    
        RotaBeanInterface rotaBean = null;
        InitialContext ctx = null;
        List<Rota> lista;
        
        String origem = (String) comboOrigemHorario.getSelectedItem();
        String destino = (String) comboDestinoHorario.getSelectedItem();
        
        try {
            ctx = new InitialContext();
            rotaBean = (RotaBeanInterface) ctx.lookup("ejb/RotaBean");
            lista = rotaBean.listar();

            for(int i=0; i<lista.size();i++){
                if(lista.get(i).getDestinoRota().equals(destino) && lista.get(i).getOrigemRota().equals(origem)){
                    comboHorario.addItem(lista.get(i).getHorario());
                    comboDataHorario.addItem(lista.get(i).getDatas());
                }
            }
        } catch (NamingException ex) {
            Logger.getLogger(TelaVendaHorario.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_carregarRotasActionPerformed

private void comboDataHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDataHorarioActionPerformed
    String horarioSelecionado = (String)comboHorario.getItemAt(comboDataHorario.getSelectedIndex());
    comboHorario.removeAllItems();
    comboHorario.addItem(horarioSelecionado);
}//GEN-LAST:event_comboDataHorarioActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManutencaoRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManutencaoRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManutencaoRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManutencaoRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManutencaoRotas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IncluirRota;
    private javax.swing.JButton alterarHorario;
    private javax.swing.JButton carregarRotas;
    private javax.swing.JComboBox comboDataHorario;
    private javax.swing.JComboBox comboDestino;
    private javax.swing.JComboBox comboDestinoHorario;
    private javax.swing.JComboBox comboHorario;
    private javax.swing.JComboBox comboOrigem;
    private javax.swing.JComboBox comboOrigemHorario;
    private javax.swing.JComboBox comboPreco;
    private javax.swing.JTextField datas;
    private javax.swing.JTextField horario;
    private javax.swing.JButton incluirFuncionario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JTextField novoHorarioRota;
    private javax.swing.JTextField rgFuncionario;
    // End of variables declaration//GEN-END:variables
    private String[] horariosCarregados = null;
}
