package desktop;

import entidades.Funcionario;
import entidades.Passagem;
import entidades.Rota;
import interfacesBean.ClienteBeanInterface;
import interfacesBean.FuncionarioBeanInterface;
import interfacesBean.PassagemBeanInterface;
import interfacesBean.RotaBeanInterface;
import java.awt.Window;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego
 */
public class TelaVendaHorario extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVendaHorario() {
        initComponents();        
    }
    
    public TelaVendaHorario(String origem, String destino) {
        initComponents();
        this.origem.setText(origem);
        this.destino.setText(destino);
        initData(origem, destino);
        
    }
    
    private void initData(String origem, String destino){
        RotaBeanInterface rotaBean = null;
        InitialContext ctx = null;
        FuncionarioBeanInterface funcionarioBean = null;
        List<Rota> lista;
        List<Funcionario> listaFunc;
        try {
            ctx = new InitialContext();
            rotaBean = (RotaBeanInterface) ctx.lookup("ejb/RotaBean");
            funcionarioBean = (FuncionarioBeanInterface) ctx.lookup("ejb/FuncionarioBean");
            
            listaFunc = funcionarioBean.listarFuncionarios();
            
            for(int i=0; i<listaFunc.size();i++){
                comboFuncionario.addItem(listaFunc.get(i).getNomeFuncionario());
            }
            lista = rotaBean.listar();
            
            for(int i=0; i<lista.size();i++){
                if(lista.get(i).getDestinoRota().equals(destino) && lista.get(i).getOrigemRota().equals(origem)){
                    String poltronas[] = lista.get(i).getNumeroAssentosOcupados().split(",");
                    for(int j=1;j<=40;j++)
                        comboPoltronas.addItem(j);
                    for(int j=0;j<poltronas.length;j++)
                        comboPoltronas.removeItemAt(Integer.parseInt(poltronas[j])-1);
                    
                    preco.setText(String.valueOf(lista.get(i).getPreco()));
                    comboHorario.addItem(lista.get(i).getHorario());
                    comboData.addItem(lista.get(i).getDatas());
                }
            }
        } catch (NamingException ex) {
            Logger.getLogger(TelaVendaHorario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        origem = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        comboHorario = new javax.swing.JComboBox();
        comboData = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboPoltronas = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        comboFuncionario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Escolha o horário:");

        jLabel2.setText("Origem:");

        jLabel4.setText("Destino:");

        jButton1.setText("Comprar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        origem.setText("jLabel5");

        destino.setText("jLabel5");

        jLabel5.setText("Horário:");

        jLabel6.setText("Data:");

        jLabel7.setText("Poltronas Livres:");

        jLabel8.setText("Preço:");

        preco.setText("jLabel5");

        comboHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHorarioActionPerformed(evt);
            }
        });

        comboData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDataActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome do Funcionário:");

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(origem)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(destino)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(menu)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(origem)
                    .addComponent(jLabel4)
                    .addComponent(destino)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(preco)
                    .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(comboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(menu))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ações de gravação no banco da compra da passagem
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        ClienteBeanInterface clienteBean = null;
        RotaBeanInterface rotaBean = null;
        PassagemBeanInterface passagemBean = null;
        
        InitialContext ctx = null;
        
        try {
            ctx = new InitialContext();
            clienteBean = (ClienteBeanInterface) ctx.lookup("ejb/ClienteBean");
            rotaBean = (RotaBeanInterface) ctx.lookup("ejb/RotaBean");
            passagemBean = (PassagemBeanInterface) ctx.lookup("ejb/PassagemBean");
            String horario = (String)comboHorario.getSelectedItem();
            String data = (String)comboData.getSelectedItem();
            
            Rota rota = rotaBean.carregarRota(origem.getText(), destino.getText(), horario, data);
            
            rotaBean.escolherPoltrona(String.valueOf(comboPoltronas.getSelectedItem()), rota);
            
            if(clienteBean.efetuarCompraGuiche(rota, String.valueOf(comboPoltronas.getSelectedItem()), (String)comboFuncionario.getSelectedItem() )){
                JOptionPane.showMessageDialog(rootPane, "Compra Efetuada com sucesso.");
                TelaVendaHorario.this.dispose();
                
                Passagem p = passagemBean.listarPassagemGuiche(origem.getText(), destino.getText(), String.valueOf(comboPoltronas.getSelectedItem()), (String)comboData.getSelectedItem(), (String)comboHorario.getSelectedItem());
                ImprimirPassagem imprimir = new ImprimirPassagem(p);
                imprimir.setVisible(true);
            }
            
            
        } catch (NamingException ex) {
            Logger.getLogger(TelaVendaHorario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

private void comboHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHorarioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_comboHorarioActionPerformed

private void comboDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDataActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_comboDataActionPerformed

private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
    TelaVendaHorario.this.dispose();
}//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaVendaHorario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboData;
    private javax.swing.JComboBox comboFuncionario;
    private javax.swing.JComboBox comboHorario;
    private javax.swing.JComboBox comboPoltronas;
    private javax.swing.JLabel destino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton menu;
    private javax.swing.JLabel origem;
    private javax.swing.JLabel preco;
    // End of variables declaration//GEN-END:variables
}
